version: "3.9"
services:
  app:
    build:
      context: .
    volumes:
      # - .:/app
      # - /app/node_modules
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # command: npm run start:watch
