name: React CI

on:
  push:
    branches:
      - "main"

env:
  CI: false
  REACT_APP_API_URL: http://3.75.186.163
  REACT_APP_ACCESS_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE2ODI2OTY5NTh9.mi10oKfwBgc74lB12URzNTTHLlObvOiq9I41Q2SC7Z4
  REACT_APP_AUTH0_DOMAIN: dev-j5yx0w-e.us.auth0.com
  REACT_APP_AUTH0_CLIENT_ID: tMBIoDwuV0rP5JmdInvqrcZEs2Tu5Glt
  REACT_APP_AUTH0_AUDIENCE: https://internship-example.com
  REACT_APP_SERVER_URI: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Create env file
        run: |
          echo "REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}" > .env
          echo "REACT_APP_ACCESS_TOKEN=${{ env.REACT_APP_ACCESS_TOKEN }}" >> .env
          echo "REACT_APP_API_URL_TEST=${{ env.REACT_APP_API_URL_TEST }}" >> .env
          echo "REACT_APP_AUTH0_DOMAIN=${{ env.REACT_APP_AUTH0_DOMAIN }}" >> .env
          echo "REACT_APP_AUTH0_CLIENT_ID=${{ env.REACT_APP_AUTH0_CLIENT_ID }}" >> .env
          echo "REACT_APP_AUTH0_AUDIENCE=${{ env.REACT_APP_AUTH0_AUDIENCE }}" >> .env
          echo "REACT_APP_SERVER_URI=${{ env.REACT_APP_SERVER_URI }}" >> .env
          cat .env
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
